#!/usr/bin/env python3
"""
Use Case 1: Protein-Peptide Docking Using HADDOCK3

This script demonstrates how to perform protein-peptide docking using HADDOCK3.
It's perfect for docking cyclic peptides to proteins when you have structural
information about both molecules.

Author: HADDOCK3 MCP Tool
Usage: python examples/use_case_1_protein_peptide_docking.py [options]
"""

import argparse
import subprocess
import sys
from pathlib import Path
import shutil
import tempfile


def create_config_file(protein_pdb, peptide_pdb, ambig_restraints, output_dir, ncores=4):
    """
    Create a HADDOCK3 configuration file for protein-peptide docking.

    Args:
        protein_pdb (str): Path to protein PDB file
        peptide_pdb (str): Path to peptide PDB file (can contain multiple conformations)
        ambig_restraints (str): Path to ambiguous restraints file
        output_dir (str): Output directory name
        ncores (int): Number of CPU cores to use

    Returns:
        str: Configuration file content
    """
    config = f"""# ====================================================================
# Protein-Peptide Docking Configuration
# Generated by HADDOCK3 MCP Tool

# directory in which the docking will be done
run_dir = "{output_dir}"

# execution mode
mode = "local"
ncores = {ncores}

# molecules to be docked
molecules = [
    "{protein_pdb}",
    "{peptide_pdb}"
]

# ====================================================================

# Generate topologies with proper histidine states
[topoaa]
autohis = false

# Rigid body docking stage
[rigidbody]
tolerance = 20
ambig_fname = "{ambig_restraints}"
sampling = 200

# Evaluate against reference (if available)
[caprieval]

# Select top models
[seletop]
select = 20

# Flexible refinement stage
[flexref]
tolerance = 20
ambig_fname = "{ambig_restraints}"
# Define peptide as fully flexible (assuming chain B)
fle_sta_1 = 1
fle_end_1 = 50
fle_seg_1 = "B"
# Define secondary structure restraints
ssdihed = "alphabeta"
# Increase MD steps for better sampling
mdsteps_rigid = 5000
mdsteps_cool1 = 5000
mdsteps_cool2 = 10000
mdsteps_cool3 = 10000

# Final evaluation
[caprieval]

# Energy minimization refinement
[emref]
tolerance = 20
ambig_fname = "{ambig_restraints}"
# Keep peptide flexible
fle_sta_1 = 1
fle_end_1 = 50
fle_seg_1 = "B"
ssdihed = "alphabeta"

# Final evaluation
[caprieval]

# Clustering based on contact similarity
[clustfcc]
min_population = 4

# Select top clusters
[seletopclusts]
top_models = 4

# Final evaluation with all atoms
[caprieval]
allatoms = true

# ====================================================================
"""
    return config


def create_basic_restraints(output_file):
    """
    Create basic ambiguous restraints for peptide docking.
    This is a template - users should modify based on experimental data.
    """
    restraints = """!
! Basic ambiguous restraints for peptide docking
! These are example restraints - modify based on your experimental data
!
! Example: residue 1 of peptide (chain B) to residues 10-20 of protein (chain A)
!assign (chain B and resid 1) (chain A and resid 10:20) 2.0 2.0 0.0
!
! Add your experimental restraints here based on:
! - NMR chemical shift perturbations
! - Mutagenesis data
! - Cross-linking data
! - Other experimental information
!
! Example restraints (uncomment and modify as needed):
! assign (chain B and resid 5) (chain A and resid 15:25) 2.0 2.0 0.0
! assign (chain B and resid 8) (chain A and resid 30:40) 2.0 2.0 0.0
"""
    with open(output_file, 'w') as f:
        f.write(restraints)


def run_haddock3(config_file, work_dir):
    """
    Execute HADDOCK3 with the given configuration file.

    Args:
        config_file (str): Path to configuration file
        work_dir (str): Working directory

    Returns:
        tuple: (success, output_dir)
    """
    try:
        # Change to working directory
        original_dir = Path.cwd()
        Path(work_dir).mkdir(exist_ok=True)
        Path(work_dir).resolve()

        print(f"Running HADDOCK3 with configuration: {config_file}")
        print("This may take several minutes to hours depending on the system size...")

        # Run HADDOCK3
        result = subprocess.run([
            "mamba", "run", "-p", str(original_dir / "env"),
            "haddock3", str(config_file)
        ],
        cwd=work_dir,
        capture_output=True,
        text=True,
        timeout=3600  # 1 hour timeout
        )

        if result.returncode == 0:
            print("HADDOCK3 completed successfully!")
            # Find the output directory
            run_dirs = [d for d in Path(work_dir).iterdir() if d.is_dir() and d.name.startswith("run")]
            if run_dirs:
                output_dir = run_dirs[0]  # Take the first run directory
                print(f"Results available in: {output_dir}")
                return True, output_dir
        else:
            print("HADDOCK3 failed!")
            print("STDOUT:", result.stdout)
            print("STDERR:", result.stderr)
            return False, None

    except subprocess.TimeoutExpired:
        print("HADDOCK3 timed out after 1 hour")
        return False, None
    except Exception as e:
        print(f"Error running HADDOCK3: {e}")
        return False, None


def main():
    parser = argparse.ArgumentParser(
        description="Run protein-peptide docking using HADDOCK3",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # Basic usage with demo data
    python examples/use_case_1_protein_peptide_docking.py

    # Custom protein and peptide
    python examples/use_case_1_protein_peptide_docking.py \\
        --protein my_protein.pdb \\
        --peptide my_peptide.pdb \\
        --restraints my_restraints.tbl

    # High-throughput mode
    python examples/use_case_1_protein_peptide_docking.py \\
        --protein examples/data/1NX1_protein.pdb \\
        --peptide examples/data/DAIDALSSDFT_3conformations.pdb \\
        --ncores 20 \\
        --output protein_peptide_docking_run
        """
    )

    parser.add_argument("--protein",
                       default="examples/data/structures/1NX1_protein.pdb",
                       help="Path to protein PDB file")

    parser.add_argument("--peptide",
                       default="examples/data/structures/DAIDALSSDFT_3conformations.pdb",
                       help="Path to peptide PDB file (can contain multiple conformations)")

    parser.add_argument("--restraints",
                       default="examples/data/restraints/ambig.tbl",
                       help="Path to ambiguous restraints file")

    parser.add_argument("--output",
                       default="protein_peptide_docking",
                       help="Output directory name")

    parser.add_argument("--ncores", type=int, default=4,
                       help="Number of CPU cores to use")

    parser.add_argument("--work-dir",
                       default="./haddock_work",
                       help="Working directory for HADDOCK3")

    parser.add_argument("--dry-run", action="store_true",
                       help="Only create configuration file, don't run HADDOCK3")

    args = parser.parse_args()

    # Check if input files exist
    protein_path = Path(args.protein)
    peptide_path = Path(args.peptide)
    restraints_path = Path(args.restraints)

    if not protein_path.exists():
        print(f"Error: Protein file not found: {protein_path}")
        print("Use --protein to specify a different file or run with demo data")
        return 1

    if not peptide_path.exists():
        print(f"Error: Peptide file not found: {peptide_path}")
        print("Use --peptide to specify a different file or run with demo data")
        return 1

    # Create restraints file if it doesn't exist
    if not restraints_path.exists():
        print(f"Restraints file not found: {restraints_path}")
        print("Creating basic restraints template...")
        restraints_path.parent.mkdir(parents=True, exist_ok=True)
        create_basic_restraints(restraints_path)
        print(f"Basic restraints created at: {restraints_path}")
        print("Please edit this file to add your experimental restraints before running!")
        if not args.dry_run:
            return 1

    # Create working directory
    work_dir = Path(args.work_dir)
    work_dir.mkdir(exist_ok=True)

    # Generate configuration file
    config_content = create_config_file(
        protein_pdb=str(protein_path.resolve()),
        peptide_pdb=str(peptide_path.resolve()),
        ambig_restraints=str(restraints_path.resolve()),
        output_dir=args.output,
        ncores=args.ncores
    )

    config_file = work_dir / "docking_config.cfg"
    with open(config_file, 'w') as f:
        f.write(config_content)

    print(f"Configuration file created: {config_file}")

    if args.dry_run:
        print("Dry run completed. Configuration file ready.")
        print(f"To run HADDOCK3 manually: mamba activate ./env && cd {work_dir} && haddock3 {config_file.name}")
        return 0

    # Run HADDOCK3
    success, output_dir = run_haddock3(config_file, work_dir)

    if success:
        print(f"\\n🎉 Protein-peptide docking completed successfully!")
        print(f"Results are in: {output_dir}")
        print(f"\\nNext steps:")
        print(f"1. Examine the results in {output_dir}")
        print(f"2. Look at the final clusters and models")
        print(f"3. Analyze the binding interface and scores")
        return 0
    else:
        print("\\n❌ Docking failed. Check the configuration and input files.")
        return 1


if __name__ == "__main__":
    sys.exit(main())