#!/usr/bin/env python3
"""
Script: protein_peptide_docking.py
Description: Perform protein-peptide docking using HADDOCK3 for cyclic peptides

Original Use Case: examples/use_case_1_protein_peptide_docking.py
Dependencies Removed: None (was already minimal)

Usage:
    python scripts/protein_peptide_docking.py --input-protein <protein.pdb> --input-peptide <peptide.pdb> --output <output_dir>

Example:
    python scripts/protein_peptide_docking.py --input-protein examples/data/structures/1NX1_protein.pdb --input-peptide examples/data/structures/DAIDALSSDFT_3conformations.pdb --output results/docking_result
"""

# ==============================================================================
# Minimal Imports (only essential packages)
# ==============================================================================
import argparse
import subprocess
import sys
from pathlib import Path
import tempfile
from typing import Union, Optional, Dict, Any, List, Tuple
import json

# ==============================================================================
# Configuration (extracted from use case)
# ==============================================================================
DEFAULT_CONFIG = {
    "ncores": 4,
    "timeout": 3600,  # 1 hour
    "tolerance": 20,
    "sampling": 200,
    "select_top": 20,
    "flexible": {
        "start": 1,
        "end": 50,
        "segment": "B"
    },
    "md_steps": {
        "rigid": 5000,
        "cool1": 5000,
        "cool2": 10000,
        "cool3": 10000
    },
    "clustering": {
        "min_population": 4,
        "top_models": 4
    }
}

# ==============================================================================
# Inlined Utility Functions (simplified from use case)
# ==============================================================================
def create_config_file(protein_pdb: str, peptide_pdb: str, ambig_restraints: str,
                      output_dir: str, config: Dict[str, Any]) -> str:
    """
    Create a HADDOCK3 configuration file for protein-peptide docking.
    Simplified from examples/use_case_1_protein_peptide_docking.py
    """
    ncores = config.get("ncores", 4)
    tolerance = config.get("tolerance", 20)
    sampling = config.get("sampling", 200)
    select_top = config.get("select_top", 20)
    flex = config.get("flexible", {})
    md = config.get("md_steps", {})
    cluster = config.get("clustering", {})

    return f"""# ====================================================================
# Protein-Peptide Docking Configuration
# Generated by HADDOCK3 MCP Tool

# directory in which the docking will be done
run_dir = "{output_dir}"

# execution mode
mode = "local"
ncores = {ncores}

# molecules to be docked
molecules = [
    "{protein_pdb}",
    "{peptide_pdb}"
]

# ====================================================================

# Generate topologies with proper histidine states
[topoaa]
autohis = false

# Rigid body docking stage
[rigidbody]
tolerance = {tolerance}
ambig_fname = "{ambig_restraints}"
sampling = {sampling}

# Evaluate against reference (if available)
[caprieval]

# Select top models
[seletop]
select = {select_top}

# Flexible refinement stage
[flexref]
tolerance = {tolerance}
ambig_fname = "{ambig_restraints}"
# Define peptide as fully flexible (assuming chain B)
fle_sta_1 = {flex.get("start", 1)}
fle_end_1 = {flex.get("end", 50)}
fle_seg_1 = "{flex.get("segment", "B")}"
# Define secondary structure restraints
ssdihed = "alphabeta"
# Increase MD steps for better sampling
mdsteps_rigid = {md.get("rigid", 5000)}
mdsteps_cool1 = {md.get("cool1", 5000)}
mdsteps_cool2 = {md.get("cool2", 10000)}
mdsteps_cool3 = {md.get("cool3", 10000)}

# Final evaluation
[caprieval]

# Energy minimization refinement
[emref]
tolerance = {tolerance}
ambig_fname = "{ambig_restraints}"
# Keep peptide flexible
fle_sta_1 = {flex.get("start", 1)}
fle_end_1 = {flex.get("end", 50)}
fle_seg_1 = "{flex.get("segment", "B")}"
ssdihed = "alphabeta"

# Final evaluation
[caprieval]

# Clustering based on contact similarity
[clustfcc]
min_population = {cluster.get("min_population", 4)}

# Select top clusters
[seletopclusts]
top_models = {cluster.get("top_models", 4)}

# Final evaluation with all atoms
[caprieval]
allatoms = true

# ====================================================================
"""

def create_basic_restraints(output_file: Path) -> None:
    """Create basic ambiguous restraints template. Simplified from use case."""
    restraints = """!
! Basic ambiguous restraints for peptide docking
! These are example restraints - modify based on your experimental data
!
! Example: residue 1 of peptide (chain B) to residues 10-20 of protein (chain A)
!assign (chain B and resid 1) (chain A and resid 10:20) 2.0 2.0 0.0
!
! Add your experimental restraints here based on:
! - NMR chemical shift perturbations
! - Mutagenesis data
! - Cross-linking data
! - Other experimental information
!
! Example restraints (uncomment and modify as needed):
! assign (chain B and resid 5) (chain A and resid 15:25) 2.0 2.0 0.0
! assign (chain B and resid 8) (chain A and resid 30:40) 2.0 2.0 0.0
"""
    with open(output_file, 'w') as f:
        f.write(restraints)

def validate_input_file(file_path: Path, file_type: str) -> bool:
    """Validate that input file exists and has correct format."""
    if not file_path.exists():
        raise FileNotFoundError(f"{file_type} file not found: {file_path}")

    if file_type == "pdb" and not file_path.suffix.lower() == ".pdb":
        raise ValueError(f"Expected PDB file, got: {file_path.suffix}")

    return True

def run_haddock3(config_file: Path, work_dir: Path, timeout: int = 3600) -> Tuple[bool, Optional[Path]]:
    """Execute HADDOCK3 with the given configuration. Simplified from use case."""
    try:
        print(f"Running HADDOCK3 with configuration: {config_file}")
        print("This may take several minutes to hours depending on the system size...")

        # Find environment path
        env_path = Path.cwd() / "env"
        if not env_path.exists():
            # Try relative to script
            env_path = Path(__file__).parent.parent / "env"

        # Run HADDOCK3
        result = subprocess.run([
            "mamba", "run", "-p", str(env_path),
            "haddock3", str(config_file)
        ],
        cwd=work_dir,
        capture_output=True,
        text=True,
        timeout=timeout
        )

        if result.returncode == 0:
            print("HADDOCK3 completed successfully!")
            # Find the output directory
            run_dirs = [d for d in work_dir.iterdir() if d.is_dir() and d.name.startswith("run")]
            if run_dirs:
                output_dir = run_dirs[0]  # Take the first run directory
                print(f"Results available in: {output_dir}")
                return True, output_dir
        else:
            print("HADDOCK3 failed!")
            print("STDOUT:", result.stdout)
            print("STDERR:", result.stderr)
            return False, None

    except subprocess.TimeoutExpired:
        print(f"HADDOCK3 timed out after {timeout} seconds")
        return False, None
    except Exception as e:
        print(f"Error running HADDOCK3: {e}")
        return False, None

# ==============================================================================
# Core Function (main logic extracted from use case)
# ==============================================================================
def run_protein_peptide_docking(
    protein_file: Union[str, Path],
    peptide_file: Union[str, Path],
    output_dir: Optional[Union[str, Path]] = None,
    restraints_file: Optional[Union[str, Path]] = None,
    config: Optional[Dict[str, Any]] = None,
    work_dir: Optional[Union[str, Path]] = None,
    dry_run: bool = False,
    **kwargs
) -> Dict[str, Any]:
    """
    Main function for protein-peptide docking using HADDOCK3.

    Args:
        protein_file: Path to protein PDB file
        peptide_file: Path to peptide PDB file (can contain multiple conformations)
        output_dir: Output directory name for results
        restraints_file: Path to ambiguous restraints file (optional, will create template)
        config: Configuration dict (uses DEFAULT_CONFIG if not provided)
        work_dir: Working directory for HADDOCK3 (default: ./haddock_work)
        dry_run: Only create configuration file, don't run HADDOCK3
        **kwargs: Override specific config parameters

    Returns:
        Dict containing:
            - success: Whether docking completed successfully
            - output_dir: Path to output directory (if successful)
            - config_file: Path to configuration file
            - restraints_file: Path to restraints file used
            - work_dir: Working directory used
            - metadata: Execution metadata

    Example:
        >>> result = run_protein_peptide_docking("protein.pdb", "peptide.pdb", "docking_result")
        >>> print(result['output_dir'])
    """
    # Setup
    protein_file = Path(protein_file)
    peptide_file = Path(peptide_file)
    config = {**DEFAULT_CONFIG, **(config or {}), **kwargs}

    if output_dir is None:
        output_dir = "protein_peptide_docking"

    if work_dir is None:
        work_dir = Path("./haddock_work")
    else:
        work_dir = Path(work_dir)

    # Validate inputs
    validate_input_file(protein_file, "protein")
    validate_input_file(peptide_file, "peptide")

    # Create working directory
    work_dir.mkdir(exist_ok=True)

    # Handle restraints file
    if restraints_file is None:
        restraints_file = work_dir / "basic_restraints.tbl"
        create_basic_restraints(restraints_file)
        print(f"Created basic restraints template: {restraints_file}")
    else:
        restraints_file = Path(restraints_file)
        if not restraints_file.exists():
            restraints_file = work_dir / "basic_restraints.tbl"
            create_basic_restraints(restraints_file)
            print(f"Restraints file not found, created template: {restraints_file}")

    # Generate configuration file
    config_content = create_config_file(
        protein_pdb=str(protein_file.resolve()),
        peptide_pdb=str(peptide_file.resolve()),
        ambig_restraints=str(restraints_file.resolve()),
        output_dir=output_dir,
        config=config
    )

    config_file = work_dir / "docking_config.cfg"
    with open(config_file, 'w') as f:
        f.write(config_content)

    result = {
        "success": False,
        "output_dir": None,
        "config_file": str(config_file),
        "restraints_file": str(restraints_file),
        "work_dir": str(work_dir),
        "metadata": {
            "protein_file": str(protein_file),
            "peptide_file": str(peptide_file),
            "config": config,
            "dry_run": dry_run
        }
    }

    print(f"Configuration file created: {config_file}")

    if dry_run:
        print("Dry run completed. Configuration file ready.")
        result["success"] = True
        return result

    # Run HADDOCK3
    success, output_path = run_haddock3(config_file, work_dir, config.get("timeout", 3600))

    result["success"] = success
    if success and output_path:
        result["output_dir"] = str(output_path)

    return result

# ==============================================================================
# CLI Interface
# ==============================================================================
def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument('--input-protein', '-p', required=True,
                       help='Input protein PDB file path')
    parser.add_argument('--input-peptide', '-e', required=True,
                       help='Input peptide PDB file path (can contain multiple conformations)')
    parser.add_argument('--output', '-o', default="protein_peptide_docking",
                       help='Output directory name')
    parser.add_argument('--restraints', '-r',
                       help='Path to ambiguous restraints file (optional)')
    parser.add_argument('--config', '-c',
                       help='Config file (JSON)')
    parser.add_argument('--work-dir', '-w', default="./haddock_work",
                       help='Working directory for HADDOCK3')
    parser.add_argument('--ncores', type=int,
                       help='Number of CPU cores to use')
    parser.add_argument('--dry-run', action="store_true",
                       help='Only create configuration file, dont run HADDOCK3')

    args = parser.parse_args()

    # Load config if provided
    config = None
    if args.config:
        with open(args.config) as f:
            config = json.load(f)

    # Override config with CLI arguments
    cli_overrides = {}
    if args.ncores:
        cli_overrides["ncores"] = args.ncores

    # Run
    try:
        result = run_protein_peptide_docking(
            protein_file=args.input_protein,
            peptide_file=args.input_peptide,
            output_dir=args.output,
            restraints_file=args.restraints,
            config=config,
            work_dir=args.work_dir,
            dry_run=args.dry_run,
            **cli_overrides
        )

        if result["success"]:
            if args.dry_run:
                print("✅ Configuration created successfully")
                print(f"Config file: {result['config_file']}")
            else:
                print("🎉 Protein-peptide docking completed successfully!")
                print(f"Results are in: {result['output_dir']}")
        else:
            print("❌ Docking failed. Check the configuration and input files.")
            return 1

        return 0

    except Exception as e:
        print(f"Error: {e}")
        return 1

if __name__ == '__main__':
    main()